### ISSUE TITLE
Create a first plot with pandas and Matplotlib

### ISSUE THREAD

**Issue by soledadli** [soledadli/interactive-Covid-19-dashboard#7]

**Comment by EliseoBaquero** [comment]
hi, I did several plots, but we have to discuss about which one we are going to publish.
see the file "Plots with pandas and matplotlib.ipynb"

**Comment by Danaal** [comment]
Yes, I check them out, Great work! they are daily cases, and death based on country and date right?
We have included these in the app.py and the countries as a filter to check multiple countries.  and the type of graph either death or daily cases or recovered as a filter too. So, we can include all
