### ISSUE TITLE
Discussing designs of dashboard 

### ISSUE THREAD

**Issue by soledadli** [soledadli/interactive-Covid-19-dashboard#9]
what components should our dashboard have

**Comment by EliseoBaquero** [comment]
first discussion about the dashboard, what is the technology we are going to use? after a brief chat we decided to use "Streamlit"

**Comment by EliseoBaquero** [comment]
I suggest to have one parameter to decide which are those countries we are going to analyze. for example if there are five regions: Europe, Africa, Asia, North America, Central and South America. looking at the total numbers of cases and then taking the country by region with the most cases. 
Top five: USA, India, Brazil, France, South Africa. 
Then we can change chile for Brazil.

**Comment by EliseoBaquero** [comment]
our dashboard is working and it has the all minimun requirements.

**Comment by EliseoBaquero** [comment]
The template selector was damaged, I included it again and changed the location of the country option and some parts of the explanation text.
